# SPDX-FileCopyrightText: <text>Copyright 2026 Arm Limited and/or
# its affiliates <open-source-office@arm.com></text>
# SPDX-License-Identifier: Apache-2.0

"""Internal constants for the NFRU stack."""

_QAT_FAKE_QUANT_EPS = 1e-7
_RANDOM_SEED_MAX = 2**31 - 1
_DEFAULT_SCALE_FACTOR = 2
_FLOW_RESIZE_FACTOR = 2.0
_FLOW_DOWNSAMPLE_SCALE = 0.5
_NEAREST_INTERPOLATION = "nearest"
_BILINEAR_INTERPOLATION = "bilinear"

_NFRU_AUTOENCODER_INPUT_CHANNELS = 16
_NFRU_AUTOENCODER_HIDDEN_CHANNELS = 32
_NFRU_AUTOENCODER_BRANCH_CHANNELS = 16
_NFRU_AUTOENCODER_CONCAT_CHANNELS = 64
_NFRU_AUTOENCODER_OUTPUT_CHANNELS = 4
_NFRU_BATCH_NORM_MOMENTUM = 0.1
_NFRU_DEPTH_PARAM_CHANNELS = 4

_KERNEL_SIZE_1 = 1
_KERNEL_SIZE_3 = 3
_KERNEL_SIZE_5 = 5
_KERNEL_SIZE_7 = 7

_PADDING_NONE = 0
_PADDING_3X3 = (1, 1)
_PADDING_5X5 = (2, 2)
_PADDING_7X7 = (3, 3)

_STRIDE_1X1 = (1, 1)
_STRIDE_2X2 = (2, 2)

_COST_CHUNK_SIZE = 8
_UINT8_MAX = 255.0
_HALF_GRADIENT_SCALE = 2.0
_LUMA_GREEN_WEIGHT = 2.0
_BINOMIAL_NORMALIZER = 4.0
_SUBPIXEL_EPS = 1e-7
_MAX_SUBPIXEL_MAGNITUDE = 1.0
_ARGMIN_OFFSET_INTENSITY = 16.0
_JOINT_BILATERAL_KERNEL_SIZE = 5
_JOINT_BILATERAL_SIGMA_SPATIAL = 7.4
_JOINT_BILATERAL_SIGMA_INTENSITY = 0.14
_UINT8_MAX_INT = 255

_BLOCKMATCH_LEVELS = 6
_BLOCKMATCH_TEMPLATE_SIZE = 5
_BLOCKMATCH_SEARCH_RANGE = 3
_BLOCKMATCH_MEDIAN_KERNEL = (_KERNEL_SIZE_3, _KERNEL_SIZE_3)
_BLOCKMATCH_BLUR_LEVELS = (1, 2, 3, 4)
_BLOCKMATCH_LAST_BM_LEVEL = 2
