# SPDX-FileCopyrightText: <text>Copyright 2026 Arm Limited and/or
# its affiliates <open-source-office@arm.com></text>
# SPDX-License-Identifier: Apache-2.0

import numpy as np
import torch


class ArgMinCentered(torch.nn.Module):
    """Argmin with center-aware tie-breaking using multiple patterns.

    Expects the last dimension of the input to represent a flattened
    2D window of size ``(2*sz+1) x (2*sz+1)``. Computes the argmin over
    that last dimension, breaking ties by favoring positions closer to
    the center according to the selected pattern.

    Modes:
      - "default": standard argmin behavior (first index in case of ties)
      - "square": Chebyshev distance rings (squares)
      - "diamond": Manhattan distance rings (diamonds)
      - "radial": squared Euclidean distance rings (circles)
      - "spiral": spiral traversal order as generated by Motion Engine

    Returns an ``int32`` tensor of indices with shape equal to the input
    shape without the last dimension.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def forward(
        self,
        inputs: torch.Tensor,
        sz: int,
        mode: str = "default",
        cv_offset: bool = False,
        offset_intensity: float = 16.0,
    ) -> torch.Tensor:
        # pylint: disable=missing-function-docstring
        x = inputs
        device = x.device
        dtype = torch.float32

        dim = sz * 2 + 1
        num_ch = dim * dim

        if cv_offset:
            rng = torch.arange(-sz, sz + 1, device=device, dtype=dtype)
            gy, gx = torch.meshgrid(rng, rng, indexing="ij")
            pattern = torch.abs(gy) + torch.abs(gx)
            offset_mask = pattern.reshape(num_ch).to(dtype) * offset_intensity
        else:
            offset_mask = torch.zeros((num_ch,), dtype=dtype, device=device)

        x = x.to(dtype)
        x = x + offset_mask
        min_val, _ = torch.min(x, dim=-1, keepdim=True)

        default_mask = (x == min_val).to(dtype)

        if mode == "default":
            mask = default_mask
        else:
            rng = torch.arange(-sz, sz + 1, device=device, dtype=dtype)
            gy, gx = torch.meshgrid(rng, rng, indexing="ij")

            if mode == "square":
                pattern = torch.maximum(torch.abs(gy), torch.abs(gx))
            elif mode == "diamond":
                pattern = torch.abs(gy) + torch.abs(gx)
            elif mode == "radial":
                pattern = gy.pow(2) + gx.pow(2)
            elif mode == "spiral":
                pattern_np = me_spiral_pattern(sz, sz)
                pattern = torch.tensor(pattern_np, dtype=dtype, device=device)
            else:
                raise ValueError("mode for ArgMinCentered not recognized")

            # Add a small central bias using epsilon value
            epsilon = torch.tensor(1e-7, dtype=dtype, device=device)
            central_bias = (pattern.reshape(num_ch) * epsilon).to(dtype)

            central_mask = default_mask - central_bias
            central_mask_max, _ = torch.max(central_mask, dim=-1, keepdim=True)
            mask = torch.where(
                central_mask == central_mask_max,
                torch.tensor(1.0, dtype=dtype, device=device),
                torch.tensor(0.0, dtype=dtype, device=device),
            ).to(dtype)

        # Final deterministic tie-break by channel index (prefer smallest index)
        epsilon = torch.tensor(1e-7, dtype=dtype, device=device)
        bias = (
            torch.linspace(0, num_ch - 1, steps=num_ch, dtype=dtype, device=device)
            * epsilon
        ).to(dtype)
        final_mask = mask - bias
        final_mask_max, _ = torch.max(final_mask, dim=-1, keepdim=True)

        single_val = torch.where(
            final_mask == final_mask_max,
            torch.tensor(1.0, dtype=dtype, device=device),
            torch.tensor(0.0, dtype=dtype, device=device),
        )

        # Convert one-hot to index
        ch_range = torch.arange(num_ch, dtype=dtype, device=device)
        min_idx = (single_val * ch_range).sum(dim=-1).to(torch.int32)

        return min_idx


def me_spiral_pattern(sz_y: int, sz_x: int) -> np.ndarray:
    """Create a spiral traversal pattern of shape (2*sz_y+1, 2*sz_x+1)."""

    pattern = np.zeros((2 * sz_y + 1, 2 * sz_x + 1), dtype=np.float32)

    radius = sz_y
    dy_end = radius + 1
    n = 0

    for dy in range(dy_end):
        for direction in range(4):
            dx_start = -dy
            limit = 1 if (direction == 0 and dy == 0) else dy
            dx_end = limit
            for dx in range(dx_start, dx_end):
                if direction == 0:
                    wx_b = radius + dx
                    wy_b = radius + dy
                elif direction == 1:
                    wx_b = radius + dy
                    wy_b = radius - dx
                elif direction == 2:
                    wx_b = radius - dx
                    wy_b = radius - dy
                else:
                    wx_b = radius - dy
                    wy_b = radius + dx
                n += 1
                pattern[wy_b, wx_b] = n

    return pattern
